dataSet <- read.table("household_power_consumption.txt",head = TRUE, sep = ";", na.strings = "?")
dataSetSub <- subset(dataSet, Date == "1/2/2007" | Date == "2/2/2007")
dataSetSub$Date <- as.Date(dataSetSub$Date, format="%d/%m/%Y")
datetime <- paste(as.Date(dataSetSub$Date), dataSetSub$Time)
dataSetSub$Datetime <- as.POSIXct(datetime)
png(filename = "plot2.png", width = 480, height = 480)
plot(dataSetSub$Global_active_power~dataSetSub$Datetime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.off()